### ISSUE TITLE
Sorting Texts by Readability

### ISSUE THREAD

**Issue by shlomihod** [shlomihod/deep-text-eval#14]
https://www.mitpressjournals.org/doi/pdfplus/10.1162/coli.09-036-R2-08-050

**Comment by vageeshSaxena** [comment]
Reading...

**Comment by vageeshSaxena** [comment]
1) Compares the complexity of two texts using SVM.
2) if Va > Vb, output = 1
3) if Va < Vb, output = - 1
4) uses binary sorting techniques to sort texts in the order of simple to complex ones.
5) Advantage: creates the dataset while performing the action.
6) Drawbacks: only applicable to find the relative complexity of two sentences.

**Comment by vageeshSaxena** [comment]
The accuracy of the comparator for different operators and features tested on TD1.
English : 
     Concatenation - 91.67%
     Subtraction - 94.27%

Japanese :
    Concatenation - 95.47%
    Subtraction - 95.47%

**Comment by vageeshSaxena** [comment]
Accuracy ~= 90 %
