### ISSUE TITLE
Analyzing Text Complexity and Text Simplification:

### ISSUE THREAD

**Issue by shlomihod** [shlomihod/deep-text-eval#16]
https://moodle2.uni-potsdam.de/pluginfile.php/920098/mod_resource/content/1/DissBalakrishna.pdf

from moodle - stede published it

**Comment by maxseidler** [comment]
Just skimmed through the table of contents:
* Corpora
  * WeeBit
  * Common Core Standards Corpus
  * TASA corpus
  * BBC Subtitles corpus
* Again, a regression model on hand-crafted features
* Whole chapter (6) on Text Simplification as Machine Translation, but didn‘t use neural networks as far as I can tell
