### ISSUE TITLE
Download weebit

### ISSUE THREAD

**Issue by pribadihcr** [shlomihod/deep-text-eval#37]
HI @shlomihod,

Where to download weebit dataset (weebit.h5)

**Comment by shlomihod** [comment]
The dataset itself is property and you should contact [Dr. Vajjala-Balakrishna](https://sowmya.public.iastate.edu/) or [Prof. Meurers](http://www.sfs.uni-tuebingen.de/~dm/) for that. Then you can you the script in the repo to pre-process the raw files.
