### ISSUE TITLE
On Improving the Accuracy of Readability Classification using Insights from Second Language Acquisition

### ISSUE THREAD

**Issue by shlomihod** [shlomihod/deep-text-eval#4]
http://www.aclweb.org/anthology/W12-2019

**Comment by maxseidler** [comment]
* Text readability classification based on age groups:
  * 7-8 years
  * 8-9 years
  * 9-10 years
  * 11-14 years
  * 14-16 years
* they build the WeeBit corpus, couldn't find it online though
* again, many hand-crafted features were extracted
* the used an **MLP (93.3% acc when used on all features)**
  * they don't describe any specifics / hyperparameters of their MLP though
