### ISSUE TITLE
Learning to Predict Readability using Diverse Linguistic Features

### ISSUE THREAD

**Issue by shlomihod** [shlomihod/deep-text-eval#5]
http://www.aclweb.org/anthology/C10-1062

**Comment by maxseidler** [comment]
* Rating of general readability (score between 1 and 5 assigned by linguistically trained human experts)
* Quite unique and complex hand-crafted features
* Tried different ML algorithms, **bagged Decision Trees worked best with 81.7% correlation** to the expert judgement
